// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QTApi.DAL;

namespace QTApi.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20181117221023_MoreFactTables")]
    partial class MoreFactTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QTApi.Models.CatFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CatFacts");
                });

            modelBuilder.Entity("QTApi.Models.CowFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CowFacts");
                });

            modelBuilder.Entity("QTApi.Models.CrowFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CrowFacts");
                });

            modelBuilder.Entity("QTApi.Models.ElephantFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ElephantFacts");
                });

            modelBuilder.Entity("QTApi.Models.JellyfishFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("JellyfishFacts");
                });

            modelBuilder.Entity("QTApi.Models.MantisShrimpFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MantisShrimpFacts");
                });

            modelBuilder.Entity("QTApi.Models.SlothFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SlothFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
