// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QTApi.DAL;

namespace QTApi.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QTApi.Models.Animals.CatFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CatFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.CowFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CowFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.CrowFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CrowFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.DogFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DogFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.ElephantFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ElephantFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.JellyfishFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("JellyfishFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.MantisShrimpFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MantisShrimpFacts");
                });

            modelBuilder.Entity("QTApi.Models.Animals.SlothFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fact")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SlothFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
